### ISSUE TITLE
Echo of headers in Response

### ISSUE THREAD

**Issue by animesh-gupta** [apickli/apickli#51]
We have a requirement that all the headers sent in the request should be echoed as it is the response. But, currently the platform mainly cucumber is converting all the headers to lower case while getting returned in response.

Could anyone of you suggest how can we resolve this issue.

**Comment by seymen** [comment]
Sorry @animesh-gupta - a bit confused. Is this a question related to apickli or cucumber in general?

**Comment by animesh-gupta** [comment]
Hi @seymen - We are still not sure is it apickli or cucumber which is making this change in the response headers. so we need your help in this case to give some suggestions where we can make the changes.

**Comment by seymen** [comment]
Hi @animesh-gupta - I understand. I think you are referring to the old discussion of case-insensitive header field names: https://github.com/nodejs/node-v0.x-archive/issues/1954

What this basically means is that if you use "headers" property of the response object, you will get all header field names lower-cased.

node.js since introduced a new property for the request object: "rawHeaders". This is an array as opposed to a json object and contains untouched header names. 

Having said all that I am still struggling the reference to apickli here. I am guessing you have your own custom code and you are having this problem in your code as apickli lowercases the header names before comparing.
