### ISSUE TITLE
Help with authentication and authorization

### ISSUE THREAD

**Issue by pmosconi** [apickli/apickli#92]
Hi and thanks for the great work.
I'm looking for help in doing the following:

Feature: Login to external auth service, get authentication token and use it in my API

   Scenario: login and get authentication token
      Given I have basic authentication credentials user and password
      When I POST to https://external-auth-service.com   # this is not in the step definition
       Then response code should be 200
       And I store the value of body path $.token as access token

   Scenario: query restricted API endpoint
      Given I set Authorization header to ??    # how do I grab the value from access token var?
      When I GET /api/restricted
      Then response code should be 200

Trying to do this, I have 2 problems:

1. the steps definition file initializes the request to my API but not the external authorization service that I need in the first scenario
2. If I understand correctly apickly implementation, only bearer token is supported (I set bearer token) vs. a generic value in the Authorization header

Thanks in advance
paolo

**Comment by seymen** [comment]
Hi @pmosconi 

My recommendation is to keep Scenarios independent of each other as a general best practice in feature files. This will remove the dependency between them enabling you to run them independently irrespective of the ordering.

In order to achieve this, in my own specs I do a dedicated feature file to test oauth handshakes (if it is my implementation - no need to test any 3rd party auth service) and do something like this to query restricted API endpoints:

```
Scenario: query restricted api endpoint
    Given I have a valid access token
    When I GET /api/restricted
    Then response code should be 200
```

I create a new step definition to implement `Given I have a valid access token` which would use apickli functions (in code) to get the access token and add the token to the request using
```
apickli.setRequestHeader('Authorization', 'Bearer ' + token);
```
Another benefit of such an implementation (on top of the general best practice recommendations) is that you can then use `Given I have a valid access token` in all your scenarios in all your .feature files.

In v2 of apickli (which we are working on), we will remove all statements that can potentially create a dependency between scenarios - which is an anti-pattern.

**Comment by jonny64** [comment]
Hi, each step require auth
how do I implement custom auth via POST?
should I put auth in init.js inside defineSupportCode?
could you please give an example

**Comment by seymen** [comment]
If you don't want to put the same `Given` statement in each Scenario, you can pass the Authorization header value in your init code, just like this: https://github.com/apickli/apickli/blob/master/source/test/features/support/init.js#L10

Change your init to pass `Authorization` header instead of `Cache-Control`.

**Comment by jonny64** [comment]
Hi! We used http-only cookie
here what worked for me

`defineSupportCode(function({Given, When, Then}) {

	Given(/^I am a demo user$/, function(callback) {
        var callout = new apickli.Apickli('https', domain);
		callout.addRequestHeader('Content-Type', 'application/json');
		callout.addRequestHeader('Cache-Control', 'no-cache');
        callout.setRequestBody('{"data":{"login":"bla", "password": "blabla"}}');
        var self = this;
        callout.post("/_create_session", function (error, response) {
            if (error) {
                callback(new Error(error));
            }
            var cookies = response.headers ["set-cookie"];
            for (var i = 0; i < cookies.length; i++) {
				self.apickli.addCookie(cookies[i]);
            }
            callback();
        });

	});`

but this says 
(node:1) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.

**Comment by seymen** [comment]
Why are you not using the related step definition?
https://github.com/apickli/apickli/blob/master/source/test/features/httpbin.feature#L41

Regarding deprecationWarning - I guess our documentation fell a bit behind, I will update it. Check out the test to use the new cucumber syntax: https://github.com/apickli/apickli/blob/master/source/test/features/support/init.js#L8

Also can't see the relevance of this in this issue. Can you please create a new issue if you want to continue?
